### ISSUE TITLE
TODO: Migration to Spring Boot 2.3

### ISSUE THREAD

**Issue by murdos** [jhipster/generator-jhipster#11681]
I've created `spring-boot-2.3` branches on both `generator-jhipster` and `jhipster` project.
I plan to create PR against these branches to handle the multiples changes required.

##### **Overview of the impacts (identified so far)**

- [x] Elasticsearch (https://github.com/jhipster/generator-jhipster/pull/11683)
- upgrade to ES 7.6
- replace jest client by official RestHighLevelClient
- removal of the Jackson ObjectMapper
- embedded node is not started anymore

- [x] MongoDB (https://github.com/jhipster/generator-jhipster/pull/11772)
- requires the MongoDB Java Driver 4.x
- move from mongobee (not maintained) to mongock (support for driver 4.x in progress: https://github.com/cloudyrock/mongock/issues/157)

- [ ] Couchbase (https://github.com/jhipster/generator-jhipster/pull/11845)
- now uses Couchbase SDK 3
- all changes: https://docs.spring.io/spring-data/couchbase/docs/4.0.0.RELEASE/reference/html/#couchbase.migrating
- requires support for SDK3 in Couchmove: https://github.com/differentway/couchmove/issues/10

- [x] Cassandra (https://github.com/jhipster/generator-jhipster/pull/11753)
- upgrade to DataStax Driver version 4
- all changes: https://docs.spring.io/spring-data/cassandra/docs/3.0.0.RELEASE/reference/html/#cassandra.migration.2.x-to-3.x

- [x] R2DBC (#11798)
- use new official starter, replacing experimental one
- use query derivation on server entities (User, AuditEvent, ...)

**Comment by rodrigocprates** [comment]
@murdos what are the plans for this PR? if you need some help, reach out to me.
I specially need a way to use MongoDB Atlas (that will be fixed on your mongobee>mongock migration)

**Comment by murdos** [comment]
@rodrigocprates : there will be a dedicated PR for mongodb, and when once Spring Boot 2.3 is released and most issues are solved, we'll coordinate to merge the `spring-boot-2.3` branch in `master`.

Regarding mongodb, I've done the migration to mongock in a branch, but it's now waiting for mongock support of MongoDB Java Driver 4.

**Comment by mraible** [comment]
FYI... 2.2 to 2.3 migration instructions: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#upgrading-from-spring-boot-22

**Comment by atomfrede** [comment]
I think we can leverage the new features for k8s deployments (graceful shutdown, liveness & readinessprobes out of box).

**Comment by JesusTheHun** [comment]
my company uses would like to give a boost on this issue but we need an invoice. How can we proceed ?

**Comment by jdubois** [comment]
Hi @JesusTheHun - only sponsors https://www.jhipster.tech/sponsors/ like Okta can give bug bounties.
Our aim is to have long-term relationships with a few select companies, and your proposal is not something we anticipated. Maybe you can directly pay someone to help?

**Comment by jdubois** [comment]
@murdos are you coming to JHipster Code? This could be one of our tracks?
Then @JesusTheHun this would be something very new, but maybe we could find a solution with your company sponsoring the conference track (people working on this during the conference would get a gift from your company, or something similar)

**Comment by murdos** [comment]
@jdubois : No, I unfortunately can't attend the conference

**Comment by jdubois** [comment]
@murdos oh but you had a ticket I believe! Are you sure you can’t come? Budget for core competitors in France isn’t an issue.

**Comment by murdos** [comment]
@jdubois : I took a ticket for the initial date in June, but I'm not available at the new date in September.

**Comment by jdubois** [comment]
Thanks @JesusTheHun ! For working on that issue as a freelancer, @murdos you might be the best person? Otherwise maybe @avdev4j @wmarques @MathieuAA @ruddell as they are all core team members and also work as freelancers

**Comment by JesusTheHun** [comment]
If one of the pinged person is interested, please email me at jonathan dot massuchetti ignorethisitsforbots at dappit.fr

**Comment by ksilz** [comment]
@jdubois Spring Boot 2.4 will be out [in October / November](https://spring.io/blog/2020/06/29/spring-boot-2-4-0-m1-is-now-available). Maybe we should just wait for that release that's three months away?

**Comment by hanoisteve** [comment]
I need to use Spring Kafka 2.5. Is there a way to handle that now. My Spring Boot version is 2.1.8 or do I need to wait until Spring Boot gets upgraded in JHipster to 2.3?

**Comment by atomfrede** [comment]
@hanoisteve You should update to the latest jhipster release which gives you boot 2.2.x. If you have that you can try a manual migration/upgrade to boot 2.3.x.

**Comment by avdev4j** [comment]
Congratulations @murdos

**Comment by mraible** [comment]
Yeehaw! Happy to see this merged. 😆

**Comment by DanielFran** [comment]
Great job @murdos

**Comment by jdubois** [comment]
Awesome work! Don't forget the $500 bug bounty @murdos !

**Comment by salimAbdulIt** [comment]
is it actually done? Because I am trying to upgrade the monolith application and after updating, I have Spring boot 2.2.7. I use Jhipster 6.10.3. Am I missing something?

**Comment by murdos** [comment]
@salimAbdulIt : it's not released yet, it will be embedded in next major release (7)
