### ISSUE TITLE
Upgrade to Angular 13

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#16960]
##### **Overview of the feature request**

Upgrade to Angular 13 so we can take advantage of faster build times.

##### **Motivation for or Use Case**

It's good for JHipster to keep up with the major releases of libraries it depends on.

##### **Tasks**

- [x] Upgrade `ng-bootstrap` to stable
- [x] Upgrade `@angular-builders/*` to stable
- [x] Upgrade `@angular-eslint/*` to stable
- [ ] Upgrade to `rxjs@7` - optional
- [x] Migrate config
- [x] Switch from custom webpack 5 cache support to the one provided by angular-cli.

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
I was about to open the issue.

**Comment by mshima** [comment]
I will start a branch, but it should be at least a couple of weeks away.

**Comment by mshima** [comment]
@qmonmert you should merge rxjs migration https://github.com/jhipster/generator-jhipster/pull/16887 to https://github.com/jhipster/generator-jhipster/pull/16961.
And if you want to start the migration, feel free to do it.

**Comment by ksilz** [comment]
Another reason for going with Node 16 is that it’s the first node release with native Mac ARM64/M1 support. Here’s [the last Node 14 release](https://nodejs.org/download/release/v14.18.1/): It just has `*-darwin-x64*` files. Here's [the 16 one:](https://nodejs.org/download/release/v16.13.0/): It also has `*-darwin-arm64*` files.

**Comment by mraible** [comment]
This is the way.

**Comment by mshima** [comment]
@pascalgrimaud bounty claimed https://opencollective.com/generator-jhipster/expenses/75228.

**Comment by pascalgrimaud** [comment]
@mshima : approved
