### ISSUE TITLE
v8 stable release.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#23449]
##### **Overview of the feature request**

Track v8 blocking issues.

TODO:
- [x] Heroku sub gen update https://github.com/jhipster/generator-jhipster/pull/23971
- [x] Update to yeoman v7 https://github.com/jhipster/generator-jhipster/issues/23868
- [x] Generated maven project uses spring-boot version but incorrectly pulls wrong springframework https://github.com/jhipster/generator-jhipster/issues/23883
- [x] Increase recently added code test coverage to 80% (Optional) https://github.com/jhipster/generator-jhipster/pull/24051

Breaking changes:
- [x] https://github.com/jhipster/generator-jhipster/issues/19112
- [x] ~https://github.com/jhipster/generator-jhipster/issues/21821~

Migrate blueprints and check/implement individual requirements:
- [x] entity-audit: https://github.com/jhipster/generator-jhipster-entity-audit/pull/207
- [x] native https://github.com/jhipster/generator-jhipster-native/pull/85
- [x] ionic: https://github.com/jhipster/generator-jhipster-ionic/issues/927
- [x] micronaut: https://github.com/jhipster/generator-jhipster-micronaut/issues/288
- [ ] quarkus: https://github.com/jhipster/generator-jhipster-quarkus/issues/294
- [ ] react-native: https://github.com/jhipster/generator-jhipster-react-native/issues/1410
- [x] jooq cc @mshima https://github.com/jhipster/generator-jhipster-jooq/pull/19
- [ ] svelte cc @vishal423 https://github.com/jhipster/generator-jhipster-svelte/issues/1862
- [x] dotnet cc @nicolas63 https://github.com/jhipster/jhipster-dotnetcore/issues/1340
- [ ] kotlin cc @sendilkumarn https://github.com/jhipster/jhipster-kotlin/issues/378
- [x] nodejs cc @amanganiello90: https://github.com/jhipster/generator-jhipster-nodejs/issues/300
- [x] ~go cc @deepu105 ?~

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
I don't think we have to wait for all blueprints to migrate as they can migrate at their own pace

**Comment by nicolas63** [comment]
I have create the issue on the jhipter-dotnet blueprint but i need your help to migrate

**Comment by mshima** [comment]
> I have create the issue on the jhipter-dotnet blueprint but i need your help to migrate

I’ve started the migration.

**Comment by mraible** [comment]
@mshima I appreciate all the work you're doing to make JHipster 8.0 happen. Please let me know if there's anything I can do to help!

**Comment by mshima** [comment]
@mraible some help updating heroku generator would be great. We should target heroku for 8.1.

With micronaut (java) and dotnetcore (2 client generators and a server) been updated.
I would say we should go ahead and release a RC as soon as possible and final a week later.

I will take a look at ci-cd generator and nodejs and ionic blueprints this weekend.

I hope to have a simultaneous release for every migrated blueprint.

**Comment by deepu105** [comment]
I can do and RC release this weekend. Let me know if I should wait for any
ticket to be merged

**Comment by mshima** [comment]
@deepu105 any news about a new release?

**Comment by deepu105** [comment]
I waiting for confirmation. I can do the RC release tomorrow.

**Comment by mshima** [comment]
Please go ahead.

**Comment by deepu105** [comment]
Its underway. Should be out today if everything goes well or latest tomorrow

**Comment by deepu105** [comment]
RC released

**Comment by deepu105** [comment]
I can do the final release next weekend

**Comment by mshima** [comment]
https://github.com/jhipster/generator-jhipster/issues/23868 should to be considered before final.
We can keep yeoman-generator v6 or move to v7.

**Comment by mraible** [comment]
I created issues for the blueprints that didn't have them and added them to the description. I don't think these need to be completed before releasing v8.

**Comment by mraible** [comment]
We should make sure test coverage is above 80% before releasing. We're currently [failing our quality gate](https://sonarcloud.io/summary/new_code?id=jhipster-sample-application).

**Comment by deepu105** [comment]
So I guess we have below task to complete for v8 final 
- [ ] Heroku sub gen update 
- [ ] Update to yeoman v7
- [ ] Increase test coverage to 80%

**Comment by mraible** [comment]
@deepu105 Yes, I agree. I added links to the issues that exist. Maybe we should move these up to the description so they're not lost. @mshima Do you have any more to add?

**Comment by mshima** [comment]
I think https://github.com/jhipster/generator-jhipster/issues/23883 is a blocker. It’s probably in jhipster-bom.

The sonar quality gate is red due to coverage on new code, not overall. Not a blocking IMO.

**Comment by mraible** [comment]
I agree that Sonar can be disregarded. It'd be cool if the report was from scratch each time rather than incremental. 

Does the Spring dependency issue happen with a brand-new Spring Boot project? If not, it's probably related to our BOM vs Spring Boot’s.

**Comment by mshima** [comment]
It’s probably in jhipster-bom.

**Comment by mraible** [comment]
@mshima I tried creating a new micro frontends architecture using:

```
jhipster jdl reactive-mf.jdl --monorepository --workspaces
```

It gives me a bunch of warnings. Do I need to update the `reactive-mf.jdl` file to add a custom id?

```
WARNING! Microservice entities should have a custom id to make sure gateway and microservice types won't conflict
WARNING! Microservice entities should have a custom id to make sure gateway and microservice types won't conflict
WARNING! Microservice entities should have a custom id to make sure gateway and microservice types won't conflict
WARNING! Microservice entities should have a custom id to make sure gateway and microservice types won't conflict
```

**Comment by mraible** [comment]
I might've fixed https://github.com/jhipster/generator-jhipster/issues/23883. If it works, can you create a release this week, @deepu105?

**Comment by mshima** [comment]
> @mshima I tried creating a new micro frontends architecture using:
> 
> ```
> jhipster jdl reactive-mf.jdl --monorepository --workspaces
> ```
> 
> It gives me a bunch of warnings. Do I need to update the `reactive-mf.jdl` file to add a custom id?
> 
> ```
> WARNING! Microservice entities should have a custom id to make sure gateway and microservice types won't conflict
> WARNING! Microservice entities should have a custom id to make sure gateway and microservice types won't conflict
> WARNING! Microservice entities should have a custom id to make sure gateway and microservice types won't conflict
> WARNING! Microservice entities should have a custom id to make sure gateway and microservice types won't conflict
> ```

@mraible fixed in https://github.com/jhipster/generator-jhipster/pull/24046.

**Comment by mraible** [comment]
👀 Our [quality gate is looking good](https://sonarcloud.io/project/overview?id=jhipster-sample-application)!

<img width="1479" alt="Screenshot 2023-10-30 at 8 20 54 PM" src="https://github.com/jhipster/generator-jhipster/assets/17892/c9743b60-bfe5-4438-9d5d-b128f84ac3ac">

@mshima @DanielFran Do we need anything else before releasing 8.0?

**Comment by DanielFran** [comment]
@mshima Is this blocking https://github.com/jhipster/generator-jhipster/issues/24028 the release?

**Comment by mshima** [comment]
> @mshima Is this #24028 blocking the release?

It's a quite annoying bug, not sure how much the use is affected.
Are you planning to cut the release?

**Comment by mshima** [comment]
> @mshima Is this #24028 blocking the release?

This is actually jhipster v7 behavior, since we used to delegate to the local generator-jhipster.

**Comment by mraible** [comment]
@mshima What's your preference? As the primary contributor to 8.0, we're happy to follow your advice. 

@deepu105 Can you do a release today or tomorrow if everyone approves? It might be fun to release on Halloween! 👻🎃

**Comment by mshima** [comment]
One last PR https://github.com/jhipster/generator-jhipster/pull/24067.

**Comment by MarkingYang** [comment]
您好，我最近学业繁忙，无法亲自回复您的邮件。晚间查看后，会尽快给您回复。

**Comment by mraible** [comment]
@mshima I'm testing [this blog post](https://deploy-preview-1366--okta-blog.netlify.app/blog/2023/09/14/spring-boot-keycloak-kubernetes) and when I run `jhipster jdl microservices.jdl`, it still has warnings:

```
WARNING! Microservice entities should have a custom id to make sure gateway and microservice types won't conflict
WARNING! Microservice entities should have a custom id to make sure gateway and microservice types won't conflict
WARNING! Microservice entities should have a custom id to make sure gateway and microservice types won't conflict
WARNING! Microservice entities should have a custom id to make sure gateway and microservice types won't conflict
WARNING! Microservice entities should have a custom id to make sure gateway and microservice types won't conflict
```

Here's the JDL:

```
application {
  config {
    baseName gateway
    packageName com.okta.developer.gateway
    applicationType gateway
    authenticationType oauth2
    buildTool gradle
    clientFramework vue
    prodDatabaseType postgresql
    serviceDiscoveryType consul
    testFrameworks [cypress]
  }
  entities Blog, Post, Tag, Product
}

application {
  config {
    baseName blog
    packageName com.okta.developer.blog
    applicationType microservice
    authenticationType oauth2
    buildTool gradle
    databaseType neo4j
    enableHibernateCache false
    serverPort 8081
    serviceDiscoveryType consul
  }
  entities Blog, Post, Tag
}

application {
  config {
    baseName store
    packageName com.okta.developer.store
    applicationType microservice
    authenticationType oauth2
    buildTool gradle
    databaseType mongodb
    enableHibernateCache false
    serverPort 8082
    serviceDiscoveryType consul
  }
  entities Product
}

entity Blog {
  name String required minlength(3)
  handle String required minlength(2)
}

entity Post {
  title String required
  content TextBlob required
  date Instant required
}

entity Tag {
  name String required minlength(2)
}

entity Product {
  title String required
  price BigDecimal required min(0)
  image ImageBlob
}

relationship ManyToOne {
  Blog{user(login)} to User with builtInEntity
  Post{blog(name)} to Blog
}

relationship ManyToMany {
  Post{tag(name)} to Tag{post}
}

paginate Post, Tag with infinite-scroll
paginate Product with pagination

microservice Product with store
microservice Blog, Post, Tag with blog

deployment {
  deploymentType docker-compose
  appsFolders [gateway, blog, store]
  dockerRepositoryName "mraible"
}
```

**Comment by mshima** [comment]
@mraible some context of this warning is at https://github.com/jhipster/generator-jhipster/pull/23850

At the PR we started relying on the frontend type to do some conversions and failed due to id different types related to different databases (gateway uses postgres with Long ids, microservice uses cassandra with UUID ids).

We used to carry on databaseType at the entity level, but this is quite hackish and hard to maintain, and we are decoupling jdl from business.
As alternative, we are advising the user to specify the entity's id type which looks much more reliable and cleaner than carrying databaseType around at entity level.

**Comment by deepu105** [comment]
I'll do the release sometime this week

**Comment by mraible** [comment]
> As alternative, we are advising the user to specify the entity's id type which looks much more reliable and cleaner than carrying databaseType around at entity level.

How do I change my JDL to get rid of this warning?

**Comment by mshima** [comment]
> > As alternative, we are advising the user to specify the entity's id type which looks much more reliable and cleaner than carrying databaseType around at entity level.
> 
> How do I change my JDL to get rid of this warning?

Neo4J and MongoDB default primary keys are String and there is no entity served in Gateway.
Add `id String` field to every entity.

**Comment by mraible** [comment]
I can confirm that adding `id String` to the JDL makes the warning go away. Here's [the commit](https://github.com/oktadev/okta-blog/pull/1366/commits/b82ee4aea14662b2ecfb12ab416ec48995941a05) with the update. Is `required` necessary for primary keys?

**Comment by mshima** [comment]
> I can confirm that adding `id String` to the JDL makes the warning go away. Here's [the commit](https://github.com/oktadev/okta-blog/pull/1366/commits/b82ee4aea14662b2ecfb12ab416ec48995941a05) with the update. Is `required` necessary for primary keys?

No, the id should imply required.
If you want to be more aaa as

**Comment by mraible** [comment]
OK, updated in https://github.com/oktadev/okta-blog/pull/1366/commits/9f4f171f2676fedcf6bd499582a646b5ceebf41b.

In the generated Java classes, I noticed the biggest difference is removing `required` results in `@NotNull` being removed:

```diff
-    @NotNull
     @Id
     private String id;
```

**Comment by DanielFran** [comment]
@mshima approved
