### ISSUE TITLE
Remove the TODO in Angular 2

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4973]
In our Angular 2 code, we currently have 4 TODO items.

Those should be removed before we release:

- [ ] TODO replace ng-file-upload dependency by an ng2 depedency
- [ ] TODO Find a better way to format dates so that it works with NgbDatePicker
- [x] TODO: real pager implementation
- [ ] TODO Use Response class from @angular/http when the body field will be accessible directly

**Comment by jdubois** [comment]
- First item is linked to #4989
- Second item is linked to #5006

**Comment by thbt** [comment]
For the first item, I fixed it using the [File API](https://developer.mozilla.org/fr/docs/Web/API/File), since I did not find any library that would fit. It works great, if you want I can put up a PR tonight or tomorrow (since I need to learn ejs first)

**Comment by deepu105** [comment]
@thbt did you take a look at https://github.com/valor-software/ng2-file-upload

**Comment by deepu105** [comment]
@thbt I wouldnt want to use fileAPI directly as the upload feature we have is for images, blob etc so would rather use a dedicated plugin for this

**Comment by jdubois** [comment]
Just did another review:

- in fact we have 9 pending TODO
- this includes the horrible _register-transaction-hooks.ts - WTF is that???

I'm giving this a higher priority.

**Comment by jdubois** [comment]
And there are 3 more TODO in the entity sub-generator :-(
Those need to be solved too.

**Comment by deepu105** [comment]
Julien lets not worry too much about TODO as we are still in beta so it
should be understandable that there are some unfinished stuff here. May be
we can make the message more clear and polished.

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
Then at least we could comment them on our side, the end user should not get our TODOs.

**Comment by deepu105** [comment]
Yes thats a good idea we can add the comments in an ejs block :) so its not
output on the generated code

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
OK I did this in https://github.com/jhipster/generator-jhipster/commit/0db40265b2702c630deab084ecf53fe0e3a51806 so I'm removing the v4 tag

**Comment by jdubois** [comment]
Closing this as the PR are commented on our side, and then we will always have TODOs to do, so there's no need to track that
