### ISSUE TITLE
Angular improvements TODO

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#5833]
These are items descoped from #4794 to be done after getting Angular out of beta

Items with **- to verify first** needs to be checked/tested first to see if already implemented

**Angular**
- [ ] Doing a perf audit shows our Angular 4 prod build is slower and bigger than our AngularJS 1 prod build. This comes from our main js bundle. it's very big (500kb) without GZipping (gzip works really well on it, which shows there's a problem !!)
time spent executing it is too long (and that's because it's really big)
Opening it shows our compiled components in a definitely non efficient format: it works, but it's big and slow.
- [x] Optimise imports/exports and declarations using barrels and constant array spreads - **out of scope for now**
```
import * as JhiPipes from './pipe';

export const JHI_PIPES = [
    JhiPipes.CapitalizePipe,
....
    JhiPipes.TruncateWordsPipe
];

//use as ...JHI_PIPES
```
- [x] Make sub modules lazy loadable #5712
- [x] Make the builds to use AOT by default  **- to verify first**
- [ ] Set html5 mode as default url strategy @gmarziou
- [x] Improve router url conventions (especially for modal dialogs)
- [x] Improve entity model dialog Impl (https://github.com/jhipster/generator-jhipster/issues/5985#issuecomment-315335622)
- [ ] polish templates  **- to verify first**
- [ ] In toast mode the position of alert is not proper
- [ ] Improve performance where possible  **- to verify first**
- [ ] Add datetime picker for Instant/ZonedDate
- [x] Find a way to remove BaseEntity which was added to avoid circular ref (Ths is bad for type inference)
- [ ] Return observable instead of promise in principal.identity() #5884

**webpack**

- [ ] Error page handling in index when something failed (can be handled from maven/gradle as well)
- [x] Improve sass/css extraction with ExtractTextPlugin and enable css optimization for prod if needed
- [x] improve initial page load time (may be using chunks)  **- to verify first**
- [x] Enable tree shaking
- [x] optimize the redundant webpack build triggered from npm postInstall
- [x] remove app/src and target folder from `traget/www` after prod build before packaging
- [ ]  Stack trace in our travis build for JHIPSTER=app-default-from-scratch PROFILE=prod RUN_APP=0 saying Skipping file 'app/main.05bc523e175995ce3771.bundle.js' due to size. [Max size supported is 2097152, this file is 3031737] This needs to be investigated #6774 

@jhipster/developers FYI

**Comment by jdubois** [comment]
I'm pretty sure we can have good html5 mode with pushState, but yes let's postpone all those, otherwise we'll never release anything

**Comment by ndjordjevic** [comment]
Does the infinite scrolling entity option suppose to work in Angular2? I tried it and it doesn't. nhInfiniteScroll is made just for Angular1 if I'm not wrong.

**Comment by jdubois** [comment]
Just tested the prod build -> the "vendor.dll" is still there, with no hash (so it's not cacheable), I thought this was solved?
@deepu105 this seems stucked, how can I help?

**Comment by deepu105** [comment]
@jdubois yes im aware of that. @sendilkumarn is working on that in a PR using ngtools. We talked about that on the original angular todo issue. Sorry on my mobile now. @sendilkumarn do you need a hand?

**Comment by tientq** [comment]
Is anyone working on **Make sub modules lazy loadable**?

**Comment by jdubois** [comment]
So are we still completely stuck here? As far as I understand we have the AOT compilation issue #5952 that is a blocker, but for all the other points, do we have blocker issues?
I can take time next week to work on some of them. Who's also available? I'd love to have this finished before my holidays, our Angular 2/4 migration journey now started one year ago, it's time to end this...
Otherwise, can't we use Angular CLI from #5661 by @stevehouel ? The argument was that we would go much quicker if we followed our original path, and now this is starting to look like a bad decision to me.

**Comment by deepu105** [comment]
@jdubois the items in this issue are not blockers. These are improvements and can be done later.

The only blocker is the AOT ticket. I got it to work, but build time is around 14 mins, which IMO is un acceptable even for prod. Im trying another strategy to bring it down to ~ 2 mins. Anyways we will have it by today or tomorrow and hopefully we can remove alpha label by next weekend

**Comment by deepu105** [comment]
Regarding Angular CLI can someone test it with AOT build and see how long it takes. If my understanding is correct it would take the same amount of time (~14 mins)  
Most of the time spend seems to be from uglify, ngc etc. I'm trying to have the vendor libs compile seperate to reduce the time

**Comment by mraible** [comment]
Could we move the admin components to ng-jhipster to reduce the amount of TypeScript that needs to be compiled? Maybe provide "include admin components source code" as a generator option?

**Comment by jdubois** [comment]
Yes the plan is to make them optional (at least) for 2 other reasons:

- they are in the JHipster Registry now
- let's not recode those again for React

But then, if removing a few screens makes a difference, that means our build doesn't scale, so that's a bad solution

**Comment by stevehouel** [comment]
Sorry @jdubois I can not test it right now ( on holidays) but I think that
my branch is still available if someone want to clone it and see how much
time it takes to build with aot option and angular-cli.
Le dim. 2 juil. 2017 à 16:29, Julien Dubois <notifications@github.com> a
écrit :

**Comment by dancancro** [comment]
I haven't been able to get i18n to work on lazy loaded pages. Is that a big deal for this release?
https://stackoverflow.com/questions/44828107/i18n-of-lazy-loaded-components-in-jhipster-app

**Comment by deepu105** [comment]
@dancancro lazy loading is planned only for later improvement so no worries

**Comment by deepu105** [comment]
Some items are done @jdubois should be good for next release

**Comment by johnlamey** [comment]
@deepu105 will html5 mode improvement be included in next release ?

**Comment by deepu105** [comment]
@johnlamey no body is working on it so no

**Comment by aleris** [comment]
I did this for an internal project. It was very simple, just removed `{ useHash: true }` from some `RouterModule.forRoot` calls. It seems to be working OK for now for entities, administration, etc. I can make a PR for the change but maybe someone can point out why `useHash: true` was used in the first place, maybe I am missing something?

**Comment by gmarziou** [comment]
I guess you are missing deep linking feature.

**Comment by aleris** [comment]
@gmarziou deep linking is dependent on deployment server. For dev is as simple as adding `historyApiFallback: true` in `devServer` option as webback devserver already has support for redirect to index.html.  
Do you know of any other thing we should take care of?

**Comment by gmarziou** [comment]
> deep linking is dependent on deployment server

No sure I understand your point, you have a solution for dev server but there is still some work to do for the spring boot app, especially on the gateway.

**Comment by aleris** [comment]
I see. There is no proper way to differentiate client paths from other paths (e.g. API) because there is nothing inherent to differentiate them. Except maybe to make a list but this will have to be maintained. Might a simpler approach like letting client handle any 404 errors might work? So the server will redirect (server side redirect) any 404 to index.html and the angular side will handle any known routes it knows, and display a 404 page on client side for anything that is not known to it. I am not familiar at all with the gateway so it might not work like this but I will have a look.

**Comment by gmarziou** [comment]
> here is no proper way to differentiate client paths from other paths (e.g. API) because there is nothing inherent to differentiate them.

In the servlet filter code I posted in [my comment](https://github.com/jhipster/generator-jhipster/issues/4794#issuecomment-304097246), I was looking at GET requests only and using a regexp for URL matching.

Redirection on 404 error is something that could work most of the time.
There could be still some URL conflicts.

For the gateway, I thought of 2 approaches:
1. using list of routes fetched from registry
2. using a prefix for all proxied services routes

First approach cannot avoid URL conflicts.

Second approach is the safest one because it avoids URL conflicts between client and server, it would be also more consistent with what we have for monolith with /api, /management and few others. Its main drawback is that it's a breaking change. 

I'm convinced that we should refactor our URLs, maybe React and Jhipster 5 is a good opportunity for doing so.

**Comment by jdubois** [comment]
Yes let's do a fixed route.

Le 27 juil. 2017 10:45 PM, "Gaël Marziou" <notifications@github.com> a
écrit :

**Comment by jdubois** [comment]
I know this isn't finished yet but:

- No work has been done here since July
- Nobody outside the core team contributes (which is a big disappointment)
- For the core team, the current focus is on React, as Angular is good enough for most projects (and I'm totally fine with this)

-> should we close this as this won't be done? At least not done anytime soon, and we have a rule not to keep tickets opened for too long

**Comment by deepu105** [comment]
@jdubois since this is only one issue which we can kind of use as an index for angular related enhancements IMO we should keep it open as some of the items in the list are must have to make the production part more usable. If you dont want them as tickets may be we can create an improvements project in the projects board and add these here

**Comment by agoncal** [comment]
@deepu105 You wrote about BaseEntity ("Find a way to remove BaseEntity which was added to avoid circular ref"). This is a question I asked on StackOverflow ([Strong typing the client model in Angular](https://stackoverflow.com/questions/45843065/strong-typing-the-client-model-in-angular)). Is it related?

**Comment by deepu105** [comment]
@NildWild if you are planning to contribute more, feel free to do anything on this list

**Comment by sendilkumarn** [comment]
wrong user

**Comment by deepu105** [comment]
@NilsWild if you are planning to contribute more, feel free to do anything on this list

**Comment by adventmedia** [comment]
just came onboard with a JHipster generated Angular 4 project. Current webpack (dev) config does not support source maps for css (from scss source files). Would be REALLY helpful to have this!

**Comment by tibistibi** [comment]
>  Add datetime picker for Instant/ZonedDate

i'm in need of a picker for time. there seems to be at least some options. is there already a preferred one for jhipster?

on my list:

- https://indrimuska.github.io/angular-moment-picker/
- https://angular-ui.github.io/bootstrap/
- https://dalelotts.github.io/angular-bootstrap-datetimepicker/index.html

**Comment by pascalgrimaud** [comment]
@tibistiti : FYI, there is a specific ticket for that subject https://github.com/jhipster/generator-jhipster/issues/6711

**Comment by tibistibi** [comment]
Thanks thought that one was about an missing error message.

I'm trying to find out if there is already a preferred way of having a time picker in jhipster

**Comment by tibistibi** [comment]
i looked at the angular bootstrap timepicker and it kind of worked but had bugs and needs extra translation because it works on an object like this: `{hour: 13, minute: 30}`

    <ngb-timepicker [(ngModel)]="upStartTime" name="upStartTime" [spinners]="true"></ngb-timepicker>

there is an option minuteStep with which you can set the increase step but it broke the increase spinner for the minutes. so for now i will not use this one

**Comment by deepu105** [comment]
I'm closing this ticket as most of the items are done and remaining may never be done as no one seems interested

**Comment by tibistibi** [comment]
understand. just to be complete: 
the minuteStep works when adding it not as a string but as an int like this:

    <ngb-timepicker [(ngModel)]="upStartTime" name="upStartTime" [spinners]="true"></ngb-timepicker [minuteStep]="15">

(notice the [] around the minuteStep

**Comment by tibistibi** [comment]
and for anyone who wants a simple solution for adding time. i made a seperate field for time only and created an input like this:

    <input id="field_downStartTime" type="text" class="form-control" name="downStartTime" [(ngModel)]="project.downStartTime"
     placeholder="{{'global.placeholder.time' | translate}}" pattern="(2[0-3]|[0-1][0-9]):[0-5][0-9](:[0-5][0-9])?" />

**Comment by vt-appsvolt** [comment]
@deepu105 and @jdubois 

I have around 40 entities in my angular project. 
Jhipster version - 6.1.0
But I have faced the same loading issue in main.bundle.ts and other  Bundle files. When I run my app into dev mode, the loading time is around 2 mins and the same time for production.

 I tried so many things to optimize my application but not getting any positive response. Can you please help me for optimizing the time as I need to push code for production rollout.

**Comment by jdubois** [comment]
I'm sorry but I don't have the time at the moment. This is 2 years old, and recently we've done many optimizations, have you had a look at upgrading? I'm not even sure we had lazy loading at that time.

**Comment by deepu105** [comment]
Yes, the latest version of JHipster has lazy loading and tree shaking all
enabled and should produce much less bundle size and faster load time. If
you can upgrade plz do so. Else generate and new project with latest
version and compare changes with your app and pick the lazy loading related
changes

**Comment by vt-appsvolt** [comment]
@deepu105 
@jdubois 

Thanks for the sharing information. Apart from lazy Loading is any other thing I need to take care of.
And also can I move all project files from x - version to the latest version without using the command **jhipster upgrade**.

**Comment by deepu105** [comment]
You have to do it manually then. What I fo in such cases is copy the
.yo-rc.json file and the .jhipster folder with all entity json files to a
new folder and run jhipster command after upgrading to new version. Then
use something like beyond compare and pick changes required
