### ISSUE TITLE
Upgrade to Spring Cloud Edgware

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/generator-jhipster#6755]
See the announcement : 
https://spring.io/blog/2017/11/27/spring-cloud-edgware-release-available

## Overview of the issue
This is a tracking issue for upgrading the microservice stack to the new Spring Cloud release.

## Todo list
- [ ] upgrade Spring Cloud to Edgware in jhipster-dependencies [PR](https://github.com/jhipster/jhipster-dependencies/pull/26)
- [ ] upgrade Zipkin to v2 in the JHipster Console
- [ ] upgrade Kafka support to Ditmars and Kafka 1.0 or remove kafka support from the generator and delegate support to the spring cloud stream module
- [ ] upgrade Consul to 1.0.2 #6970
- [ ] document how retries/timeouts works in the current version
- [x] upgrade spring boot to 1.5.9
- [ ] remove the spring cloud stream bom import in generated pom.xml as it is included in spring cloud [PR](https://github.com/jhipster/jhipster-dependencies/pull/26)

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
That's hip!

**Comment by erikkemperman** [comment]
See also https://github.com/jhipster/jhipster-dependencies/pull/23 which updates jhipster-dependencies to spring-platform Brussels-SR6 and, transitively, spring-boot 1.5.9. 

Also, I think the explicit BOM import for spring-cloud-stream can be removed, it's included in spring-cloud and it might be better to just inherit it from there -- spring-cloud version Edgware gets spring-cloud-stream version Ditmars:
https://github.com/spring-cloud/spring-cloud-release/blob/vEdgware.RELEASE/spring-cloud-dependencies/pom.xml#L29

**Comment by PierreBesson** [comment]
Good @erikkemperman, I updated the todo list.

**Comment by erikkemperman** [comment]
@PierreBesson See https://github.com/jhipster/jhipster-dependencies/pull/26

**Comment by PierreBesson** [comment]
@erikkemperman I will test this soon. I also need if it still works with the console as I need to upgrade the ZIpkin server there.

**Comment by erikkemperman** [comment]
No rush, just wanted this on the radar to avoid duplicate effort.

**Comment by pascalgrimaud** [comment]
@PierreBesson : currently, we use `Finchley.M7` -> https://github.com/jhipster/jhipster-dependencies/blob/master/pom.xml#L95
So do you think we can close this ticket ?

**Comment by deepu105** [comment]
@PierreBesson @pascalgrimaud @jdubois I see merged PRS here, so is it done? I didnt follow this very closeley

**Comment by pascalgrimaud** [comment]
yes I think it's done, let close this
