### ISSUE TITLE
TODO : Reactive/Webflux support

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#7608]
I have created a branch `reactive` to support reactive/webflux applications.

This issue is a TODO list for what remains:

- [x] Reactive DomainUserDetailsService (authentication) (@cbornet)
- [x] Account resource (@cbornet)
- [x] Security Audits (@cbornet #10405)
- [x] Serve front-end / static content (@cbornet)
- [x] Configure Locale resolver  (@cbornet)
- [x] Configure CORS  (@cbornet)
- [x] Exception handling (Problem) (https://github.com/zalando/problem-spring-web/pull/182)(@cbornet)
- [x] Http session / Cookie auth (#9326)  (@cbornet)
- [x] OAuth2 (@mraible  #11117)
- [x] SQL with R2DBC + reactor-pool (@cbornet #11439)
- [x] Cassandra (@cbornet in #9373)
- [x] Disable caching (@cbornet #10107)
- [x] Couchbase (@tchlyah in https://github.com/jhipster/generator-jhipster/pull/8997)
- [x] Skip user management on monolith and no database (#11014)(@cbornet)
- [x] API first (#8532) (@cbornet)
- [x] Server resources tests with WebTestClient
  - [x] User  (@cbornet)
  - [x] Account (@cbornet)
  - [x] Logs  (@cbornet)
- [x] Server resources
  - [x] User  (@cbornet)
  - [x] Logs  (@cbornet)
- [x] With service registry (Eureka)  (@cbornet)
- [x] Micro-service app  (@cbornet)
- [x] Metrics reporting with micrometer  (@cbornet)
- [x] Tune logback (#10462)(@cbornet)
- [x] Kafka option (#10935)(@cbornet)
- [x] Add BlockHound and Hooks.onOperatorDebug() during tests (#11009)(@cbornet)
- [x] Entity generator (#11416)(@murdos)

Blocked:
* Session Remember-me. (see https://github.com/spring-projects/spring-security/issues/5504)
* WebSockets option: no support for [security](https://github.com/spring-projects/spring-security/issues/5188) nor [STOMP](https://github.com/spring-projects/spring-framework/issues/19101)
* Springfox /swagger-ui (supported by future v3 of Springfox : https://github.com/springfox/springfox/issues/1773)
* Auditing : https://github.com/spring-projects/spring-security/issues/4961 and https://jira.spring.io/browse/DATACMNS-1231
* Caching : https://github.com/spring-projects/spring-framework/issues/17920

Later:
- [ ] WebClient configuration including integration with Netflix (in place of FeignClient) 
- [ ] RSocket client/server (same as WS)

**Comment by cbornet** [comment]
Note on R2DBC : currently it's not perf enough to be considered in a real life app mainly because it doesn't support connection pooling yet. See progress on this in https://github.com/reactor/reactor/issues/651

**Comment by cbornet** [comment]
Cool ! Micrometer just works with Webflux !

**Comment by DanielFran** [comment]
@cbornet Seems in springfox project integration with SB 2.1.x has been merged... and it includes migration to swagger-ui 3.

**Comment by cbornet** [comment]
Yes. We need the v3 of Springfox to be released. I tried to use the snapshot but had a lot of issues so I'll wait for the release. As for swagger UI, we don't use the one packaged by Springfox so we could already do the move.

**Comment by cbornet** [comment]
Reactor now supports a [reactive pool](https://github.com/reactor/reactor-pool) that could be useful for R2DBC connection pooling

**Comment by mp911de** [comment]
R2DBC 0.8.0 M8 is out now.

**Comment by cbornet** [comment]
Yes. I tested it and it does improve performance a lot. Great job !

**Comment by jdubois** [comment]
As this is a very big one, I'm increasing the bug bounty to $500 !

**Comment by cbornet** [comment]
It would probably be better to open individual issues for this. But I didn't want to cripple the issue tracker. Maybe I could open a dedicated repo where we can add smaller issues with smaller bounties ?

**Comment by jdubois** [comment]
@cbornet you can put them on the main repo as long as we have the correct labels (maybe have a specific one for reactive), and the original plan was to have smaller $100 tickets. So if you do that we could split/move the bug bounty, but at the moment we only got this one.

**Comment by cbornet** [comment]
About caching, there's currently no support for [@Cacheable](https://github.com/spring-projects/spring-framework/issues/17920) in spring data reactive. A [reactor add-on](https://stackoverflow.com/a/48156827) can be used to wrap the CacheManager. Note that the CacheManager being a blocking API, it kind of defeats the async non-blocking pattern. For now, the best solution seems to be to disable the cache option for reactive apps.

**Comment by cbornet** [comment]
There's currently no support for [security](https://github.com/spring-projects/spring-security/issues/5188) nor [STOMP](https://github.com/spring-projects/spring-framework/issues/19101) for websockets in WebFlux. So it seems hard to do much more than a hello world right now...
The recommendation seems to be to evaluate RSocket instead which I can only agree with :smiley:

**Comment by mraible** [comment]
@cbornet I'd like to help get the Reactive support "good enough" to release as GA. Is this issue's TODO list up-to-date? If so, I can start working on OAuth support and maybe entity generation. Let me know.

**Comment by cbornet** [comment]
Yes the TODO is up to date. Your help on the OAuth support is very welcome if course 😀! Thanks a lot Matt !

**Comment by mraible** [comment]
Do you think all checkboxes are necessary for a GA release or can we hide some and add them as we implement them?

**Comment by cbornet** [comment]
Yes we can define what we want for a GA. For instance, do you think SQL support is mandatory ?

**Comment by mraible** [comment]
If it's easy to integrate R2DBC, then yes.

**Comment by mraible** [comment]
@cbornet I started working on OAuth support in https://github.com/jhipster/generator-jhipster/pull/11049. I created a sample app at https://github.com/mraible/jhipster-reactive-monolith-oauth2 and [a PR](https://github.com/mraible/jhipster-reactive-monolith-oauth2/pull/1) that makes login work. 

I still need to add non-blocking support in `UserService`. I added `// todo:` comments in my PR for code that needs to be uncommented and fixed.

**Comment by cbornet** [comment]
Cool ! On my side, I've made progress with the r2dbc support. It's almost ready but it requires that we first upgrade to Spring 5.2.

**Comment by mraible** [comment]
@cbornet Do you know how to get tests to work? I'm getting the following error when I run `./mvnw test`. It seems like none of the tests with `@SpringBootTest` are being executed.

```
WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
java.lang.NoClassDefFoundError: junit/runner/Version
	at org.junit.vintage.engine.JUnit4VersionCheck.checkSupported(JUnit4VersionCheck.java:32)
	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:61)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:177)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:164)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:127)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
```

**Comment by mraible** [comment]
@cbornet Nevermind. I was able to solve this warning by changing the junit exclusion to:

```xml
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-test</artifactId>
  <scope>test</scope>
  <exclusions>
    <exclusion>
      <groupId>org.junit.vintage</groupId>
      <artifactId>junit-vintage-engine</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```

I also realized you have to run `mvn verify` for the Spring Boot tests to run.

**Comment by mraible** [comment]
@cbornet I don't see Spring Cloud Gateway as one of the items in this issue's description. I have OAuth working with Spring Cloud Gateway in https://github.com/jhipster/generator-jhipster/pull/11223. I still need to add JWT support. Not sure if Consul is necessary since we're still in Alpha mode.

**Comment by mraible** [comment]
FYI... it seems like a reactive monolith doesn't pass `./mvnw verify`.

```
[ERROR] Failures:
[ERROR]   ExceptionTranslatorIT.testMethodArgumentNotValid:41 Response header 'Content-Type' expected:<application/problem+json> but was:<text/plain>

> POST /api/exception-translator-test/method-argument
> WebTestClient-Request-Id: [17]
> Content-Type: [application/json]
> Content-Length: [2]

{}

< 403 FORBIDDEN Forbidden
< Content-Type: [text/plain]
< Cache-Control: [no-cache, no-store, max-age=0, must-revalidate]
< Pragma: [no-cache]
< Expires: [0]
< X-Content-Type-Options: [nosniff]
< X-XSS-Protection: [1 ; mode=block]
< Feature-Policy: [geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; fullscreen 'self'; payment 'none']
< Content-Security-Policy: [default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:]
< Referrer-Policy: [strict-origin-when-cross-origin]

CSRF Token has been associated to this client

[ERROR]   ExceptionTranslatorIT.testMethodNotSupported:96 Status expected:<405> but was:<403>

> POST /api/exception-translator-test/access-denied
> WebTestClient-Request-Id: [15]

No content

< 403 FORBIDDEN Forbidden
< Content-Type: [text/plain]
< Cache-Control: [no-cache, no-store, max-age=0, must-revalidate]
< Pragma: [no-cache]
< Expires: [0]
< X-Content-Type-Options: [nosniff]
< X-XSS-Protection: [1 ; mode=block]
< Feature-Policy: [geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; fullscreen 'self'; payment 'none']
< Content-Security-Policy: [default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:]
< Referrer-Policy: [strict-origin-when-cross-origin]

CSRF Token has been associated to this client

[INFO]
[ERROR] Tests run: 33, Failures: 2, Errors: 0, Skipped: 0
```

Here's my .yo-rc.json:

```json
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.7.1",
    "applicationType": "monolith",
    "baseName": "mono",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1582154650121,
    "testFrameworks": ["protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en"],
    "blueprints": [],
    "reactive": true
  }
}
```

**Comment by mraible** [comment]
@jhipster/developers Spring Cloud Gateway integration seems to be [good to go](https://github.com/jhipster/generator-jhipster/pull/11223)! Should I merge?

I kept the Zuul code for Zuul for non-reactive apps. This means that we're just adding a feature, no breaking changes.

**Comment by mraible** [comment]
@cbornet Adding support for Elasticsearch seems to be the last thing to do. Is that correct?

**Comment by cbornet** [comment]
Indeed ! We could even open another issue for ES and close this one.

**Comment by mraible** [comment]
@cbornet I created https://github.com/jhipster/generator-jhipster/issues/11536 for Elasticsearch support.

**Comment by cbornet** [comment]
OK. I'm removing it from here since it has it's own issue.
So we just need to merge #11009 and this issue can be closed.

**Comment by cbornet** [comment]
All items are done so I guess we can close this big one.
Many thanks to @mraible for the work on OIDC and to @tchlyah for the couchbase support.
How do you think the bounty should be shared ?

**Comment by pascalgrimaud** [comment]
@cbornet : I disagree about sharing the bounty because:
- it was so much work to achieve this
- as you was the lead on this part, you should take the main bounty (500$) and it will be well deserved. But I'm not sure it would be enough... we can discuss if you think it's not enough :)
- for other people who participated to this ticket, we can do separate bounty (100$ or more if you think it's deserved) for each part

Just tell me.
What do you think ?

**Comment by deepu105** [comment]
I also agree with Pascal, we have enough money to give more bounty

Thanks & Regards,
Deepu

**Comment by tchlyah** [comment]
Thank you @cbornet, glad to hear that I helped.

I totally agree with @pascalgrimaud, you deserve the whole bounty, and even more.

**Comment by mraible** [comment]
@cbornet You did as much work as I did on the OIDC integration! +1 to give you the whole bounty.

**Comment by cbornet** [comment]
Last time I checked, reactive WebSocket support was incomplete in Spring (no security and no STOMP). So it's currently not supported by JHipster.
