### ISSUE TITLE
Upgrade to spring-boot 2.1.x

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#8683]
With the launch of new spring-boot 2.1.0, it is time to continue the work started in https://github.com/jhipster/generator-jhipster/issues/8047.

See: https://spring.io/blog/2018/10/30/spring-boot-2-1-0 & https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes

TODO:
- [x] Create specific branches 'spring-boot_2.1.0' in jhispter dependencies and main generator
- [x] Update Liquibase to 3.6.2
- [x] [Allow bean overriding](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#bean-overriding)
- [x] Update spring-security-oauth2-autoconfigure
- [x] Update Dropwizard Metrics to 4.0.3 ([Moved JMX reporting to the metrics-jmx module](https://github.com/dropwizard/metrics/releases/tag/v4.0.0))
- [x] Substitute deprecated function acceptsProfiles(string...) by acceptsProfiles(Profiles.of(string)...)
- [x] Spring-cloud upgrade to Greenwish.M3
- [x] [TaskExecutor](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#task-execution) & [TaskScheduling](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#task-scheduling) changes
- [x] [Micrometer 'all' sla handling](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#micrometer-all-sla-handling)
- [x] [JCacheRegionFactory changes](https://hibernate.atlassian.net/browse/HHH-12702)
- [x] Update Spring-data-jest to 3.2.0.RELEASE ([Elasticsearch to 6.2.2](https://github.com/VanRoy/spring-data-jest/issues/55))
- [x] Downgrade to Elasticsearch 6.2.2 (instead of 6.4.3) because [spring-data-elasticsearch Lovelace-SR3 is targetting 6.2.2](https://github.com/spring-projects/spring-data-elasticsearch/blob/3.1.x/pom.xml#L22)
- [x] Upgrade to spring-boot 2.1.1
- [x] Upgrade to Couchbase 6.0.0
- [x] Migrate to [Hazelcast-hibernate53](https://github.com/hazelcast/hazelcast-hibernate5/releases/tag/v1.3.0) (see https://github.com/hazelcast/hazelcast-hibernate5/pull/48)
- [x] Update Infinispan to 9.4.4 (see https://github.com/infinispan/infinispan/pull/6496,  https://github.com/infinispan/infinispan/pull/6511 and https://github.com/infinispan/infinispan-spring-boot/issues/74)
- [x] Update infinispan-spring-boot to 2.1.1.Final (see https://github.com/infinispan/infinispan-spring-boot/issues/67 and https://github.com/infinispan/infinispan-spring-boot/pull/82)
- [x] Update Spring-cloud version to [Greenwich.RC1](https://spring.io/blog/2018/12/12/spring-cloud-greenwich-rc1-available-now)
- [x] Update Spring-cloud version to [Greenwich.RC2](https://spring.io/blog/2018/12/21/spring-cloud-greenwich-rc2-is-now-available)
- [x] Cassandra upgrade
- [x] Update micrometer to 1.1.2 expected Jan 10th (https://github.com/micrometer-metrics/micrometer/milestones)
- [x] Update spring-boot to 2.1.2 expected Jan 11th (https://github.com/spring-projects/spring-boot/milestones)
- [x] Update spring-security-oauth2-boot to 2.1.2 expected Jan 11th (https://github.com/spring-projects/spring-security-oauth2-boot/milestones)
- [x] Update infinispan-spring-boot to 2.1.2 (https://github.com/infinispan/infinispan-spring-boot/issues/88)
- [x] Fix floatType for mariadb in liquibase script (https://github.com/jhipster/generator-jhipster/pull/9063)
- [x] Update spring-cloud to Greenwich.RELEASE expected Jan 22th (https://github.com/spring-cloud/spring-cloud-release/milestones)

Bonus: JDK9+ compatibility
- [x] Substitute @PostConstruct by InitializingBean implementation
- [x] Substitute @PreDestroy by DisposableBean implementation
- [x] JDK 11 support

@jhipster/developers please add here if I missed any evolution/impact

**Comment by mraible** [comment]
I don't think we _have_ to upgrade to Spring Security's OIDC support, but we certainly can. It will allow users to configure more than one OIDC provider, so if they wanted to add Google or Facebook, they could.

FWIW, I also have global SSO logout working. I'll create a PR for that against the current version sometime this week.

**Comment by DanielFran** [comment]
@jhipster/developers Anyone might help to fix last issues?

**Comment by pascalgrimaud** [comment]
@DanielFran : if needed, we could focus on this, this tuesday at our JHipster Day at Ippon

**Comment by jdubois** [comment]
I'm definitely very interested, I'll have a look during the week.

**Comment by DanielFran** [comment]
Actually I have an issue with AsyncLiquibase due to changes with taskexecutor and also an error with missing javassist in clathpath... :(

**Comment by mraible** [comment]
Something I noticed in the [2.1 release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes) today:

**Elasticsearch REST Clients**
As an alternative option to Jest, auto-configurations for `RestClient` and `RestHighLevelClient` are provided with configurable options from the `spring.elasticsearch.rest.*` namespace.

I'm not sure that we want to move away from Spring Data Jest for Elasticsearch, but if we do, this option might help with that.

**Comment by DanielFran** [comment]
@jdubois @PierreBesson I updated spring-cloud dependency to Greenwish.M2.

**Comment by jdubois** [comment]
Thanks @DanielFran ! Sorry I didn't have the time yet to work on this

**Comment by DanielFran** [comment]
@jdubois me neither. It is just that I am stuck with taskexecutor and also an error with missing javassist in classpath... :(

**Comment by jdubois** [comment]
I did quite a number of commits in the Spring Boot 2.1 branches, fixing some JDK 11 issues and Async configuration issues.

There is one big issue with Hazelcast, as it currently does not support Hibernate 5.3 (and we can't downgrade, because Hibernate 5.3 brings JDK 9 support). See https://github.com/hazelcast/hazelcast-hibernate5/issues/44 for more information -> we need to have the solution at https://github.com/hazelcast/hazelcast-hibernate5/pull/48 as using the solution at https://github.com/hazelcast/hazelcast-hibernate5/issues/44#issuecomment-403793289 is not enough for us (as we have a singleton and need to re-use it)

**Comment by DanielFran** [comment]
ElasticSearch version is now updated and seems working.

pending issues:
- issue with 1 changeset (see https://travis-ci.org/jhipster/jhipster/jobs/460018201#L5997)
- infinispan (see https://travis-ci.org/jhipster/jhipster/jobs/460018207#L4576)
- cassandra (see https://travis-ci.org/jhipster/jhipster/jobs/460018210#L2781)
- hazelcast: bug detailed by @jdubois

**Comment by jdubois** [comment]
Cassandra doesn't work as Cassandra 3.x does not support Java 9 and above. As we use CassandraUnit in our tests, which runs an embedded Cassandra, there is no way our tests can pass. Java 9+ support is scheduled for Cassandra 4, but there is no release date available as of today. The main solution to me would be to use TestContainers, like we do for Couchbase.

Now I'm going to tell unpleasant things, but as we have full statistics publicly available on https://start.jhipster.tech/#/statistics we can see that, for last month:

- Cassandra is used by 0,33% of users
- Couchbase is used by 0,17% of users
- Infinispan is used by 0,64% of users

Those three options give us a lot of maintenance work, and are probably going to be blockers for our upcoming JDK 11 and Spring Boot 2.1 support. Considering that nearly nobody uses them, and also that they the 3 of them are backed by companies with tons of $$$ which do not contribute at all to the project, I think we should have a clear and open discussion on removing those options. I'll post this on the dev mailing list right now.

**Comment by jdubois** [comment]
Just use the one from last month. We have some bad data at the beginning of the year, which explain your higher numbers.

**Comment by avdev4j** [comment]
Some news about Elasticsearch : 
Both spring data jest and spring data elasticSearch need 6.2.2 elasticSearch API version.
Spring boot 2.1.1.Release set (in Spring boot dependencies POM) the elasticSearch version on 6.4.3.

Unfortunatly the XContentBuilder class has been modified and do not support string() method. String method is using somewhere by spring data jest.
That's why, at startup, spring boot fire an error.

To fix it I have just open a PR ([https://github.com/jhipster/jhipster/pull/135](https://github.com/jhipster/jhipster/pull/135)) to force the ElasticSearch version on 6.2.2.

At the same time the docker image is not longer working because of version changement (2 to 2.2) and remove "-E" in command. It seems no longer support on ES 6+. #8927 

Both docker and embedded ElasticSearch runs should work now.

thanks to @juliensadaoui and @pascalgrimaud for helping 👍

**Comment by DanielFran** [comment]
I open issue https://github.com/VanRoy/spring-data-jest/issues/102 to fix those issues.

**Comment by DanielFran** [comment]
New status:
- Infinispan KO
- Cassandra KO
- Couchbase OK
- Elasticsearch downgrade to 6.2.2 OK

**Comment by jdubois** [comment]
Thanks @DanielFran ! As discussed earlier and on the mailing list, we will remove the Infinspan/Cassandra/Couchbase options, but as cleanly as possible:

- I will create tickets for each of them, for detailed explanation & discussion
- If the technology is currently broken (Cassandra & Infinispan), I will remove the option as long as it's broken (the code is not deleted, only the option is removed, so you can't select it)
- For each technology, I will try to find a team of people to manage it: if they are ready to do the upgrades, the option will stay enabled as soon as they correct the issues
- We will try to migrate those to blueprints, but this is a lot of work so those teams should be very motivated by this migration. But this will give them much more freedom.

**Comment by DanielFran** [comment]
About elasticsearch, actually there is no bug, [spring-data-elasticsearch Lovelace-SR3 is targetting 6.2.2](https://github.com/spring-projects/spring-data-elasticsearch/blob/3.1.x/pom.xml#L22), so we need to keep using that version instead of [6.4.3 defined in spring-boot 2.1.1](https://github.com/spring-projects/spring-boot/releases/tag/v2.1.1.RELEASE).

**Comment by Mahdihp** [comment]
Upgrade to spring-boot 2.1

**Comment by gmarziou** [comment]
@Mahdihp What are you trying to say with this comment and also https://github.com/jhipster/generator-jhipster/issues/5970#issuecomment-444638306 ?

**Comment by PierreBesson** [comment]
An important thing to do for JDK11 support is to upgrade the docs and recommend to install java throught the adoptopenjdk site.

**Comment by mraible** [comment]
@PierreBesson We could also just recommend [SDKMAN!](https://sdkman.io/) for Java 11 installation. That's what I use/recommend.

**Comment by PierreBesson** [comment]
Sdkman will install the Zulu jdk, I think we should recommend the regular jdk install provided by adoptopenjdk. They also have a docker image.

**Comment by mraible** [comment]
SDKMAN allows OpenJDK as well.

```
$ sdk list java
================================================================================
Available Java Versions
================================================================================
     12.ea.20-open       1.0.0-rc-8-grl
   + 11.ea.26-open
     11.0.1-zulu
   * 11.0.1-open
   + 11.0.0-open
     10.0.2-zulu
     10.0.2-open
     9.0.7-zulu
     9.0.4-open
     8.0.192-zulu
     8.0.191-oracle
 > + 8.0.181-zulu
     7.0.181-zulu
     1.0.0-rc-10-grl
     1.0.0-rc-9-grl
```

**Comment by jdubois** [comment]
I'm merging #9005 which should fix the Cassandra tests, once a new release of JHipster Dependencies is done.

-> how about a 2.1.0 release of JHipster BOM + framework, which would use Spring Boot 2.1?

**Comment by DanielFran** [comment]
Would be awesome! 🥇 

Do you think we could then create a beta version of the generator?

**Comment by jdubois** [comment]
@DanielFran first I would like a green build of the Spring Boot 2.1 branch of jhipster/jhipster, and then I'll release new versions of JHipster dependencies and framework. And after that, yes we can do beta versions of the generator.

**Comment by DanielFran** [comment]
@jhipster/developers all tasks are done!

**Comment by avdev4j** [comment]
Sounds great !

**Comment by rburgst** [comment]
when can we expect an official release with spring boot 2.1?

**Comment by pascalgrimaud** [comment]
@rburgst : as we work on JHipster during our free time, we can't give you a date. We hope very soon.
If you need it for your projects, you can use master branch ;
- https://github.com/jhipster/generator-jhipster
- https://github.com/jhipster/jhipster
